# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=datetime.datetime(2016, 3, 29, 17, 45, 58, 822937, tzinfo=utc), upload_to='documents'),
            preserve_default=False,
        ),
    ]
