# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='document',
        ),
        migrations.AddField(
            model_name='table',
            name='file',
            field=models.FileField(default=datetime.datetime(2016, 3, 31, 19, 16, 32, 824686, tzinfo=utc), upload_to='documents'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
