# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20160331_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Viz',
        ),
    ]
