# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20160331_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='viz',
            name='encoded_id',
            field=models.TextField(default=datetime.datetime(2016, 3, 31, 20, 1, 17, 417500, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
