# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_viz_encoded_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viz',
            name='chatter',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='viz',
            name='encoded_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='viz',
            name='source',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='viz',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
