# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20160331_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viz',
            name='encoded_id',
        ),
        migrations.AddField(
            model_name='viz',
            name='json',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents'),
        ),
    ]
