# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20160331_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viz',
            new_name='TableViz',
        ),
    ]
